package com.example.user.task_4.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.user.task_4.database.RssItem;

import com.example.user.task_4.database.RssItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rssItemDaoConfig;

    private final RssItemDao rssItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rssItemDaoConfig = daoConfigMap.get(RssItemDao.class).clone();
        rssItemDaoConfig.initIdentityScope(type);

        rssItemDao = new RssItemDao(rssItemDaoConfig, this);

        registerDao(RssItem.class, rssItemDao);
    }
    
    public void clear() {
        rssItemDaoConfig.clearIdentityScope();
    }

    public RssItemDao getRssItemDao() {
        return rssItemDao;
    }

}
