package com.example.user.task_4.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RSS_ITEM".
 */
@Entity
public class RssItem {

    @Id(autoincrement = true)
    private Long id;
    private String title;
    private String link;

    @Generated
    public RssItem() {
    }

    public RssItem(Long id) {
        this.id = id;
    }

    @Generated
    public RssItem(Long id, String title, String link) {
        this.id = id;
        this.title = title;
        this.link = link;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

}
